[server]
port = 1111 # Gping's port
router = "http://example.com/api" # Router server URL
solana_rpc = "https://api.mainnet-beta.solana.com" # Solana RPC URL

[key]
key_path = "/Users/zzase/go/src/github.com/Seoulana-DePing/gping/keys/private_key.bin" # Path to the private key file
address = "A1DgfEAvqcnYivZJv814PKRQLZ63hADxjLrDTGm1S3TL" # Corresponding Solana address

[vault]
address = "ExampleVaultAddress123456789" # Vault contract address
fee_ratio = "0.05" # 5% fee ratio

# List of other Gping nodes in the P2P network
[[gpings]]
url = "ws://gping1.example.com/ws"
address = "GpingNode1SolanaAddress123456789"

[[gpings]]
url = "ws://gping2.example.com/ws"
address = "GpingNode2SolanaAddress123456789"

[[gpings]]
url = "ws://gping3.example.com/ws"
address = "GpingNode3SolanaAddress123456789"

[tpings]
addresses = [
  "TpingAddress1123456789",
  "TpingAddress2123456789",
  "TpingAddress3123456789",
  "TpingAddress4123456789",
  "TpingAddress5123456789"
] 